const doctors = {
  hospitals: [
    {
      hospitalName: "Square Hospitals Ltd.",
      hospitalArea: "Panthapath, Dhaka, Bangladesh",
      doctors: [
        {
          name: "Dr. Nazia Khan",
          degree: "MBBS, MRCP",
          speciality: "Internal Medicine",
          workingIn: "Square Hospitals Ltd.",
          totalExperience: "15 years",
        },
        {
          name: "Dr. Siddiqur Rahman",
          degree: "MBBS, FCPS",
          speciality: "Pediatrics",
          workingIn: "Square Hospitals Ltd.",
          totalExperience: "11 years",
        },
        {
          name: "Dr. Aisha Ahmed",
          degree: "MBBS, FCPS",
          speciality: "Gastroenterology",
          workingIn: "Square Hospitals Ltd.",
          totalExperience: "13 years",
        },
        {
          name: "Dr. Nusrat Islam",
          degree: "MBBS, FCPS",
          speciality: "Psychiatry",
          workingIn: "Square Hospitals Ltd.",
          totalExperience: "10 years",
        },
        {
          name: "Dr. Farzana Khan",
          degree: "MBBS, MD",
          speciality: "Psychology",
          workingIn: "Square Hospitals Ltd.",
          totalExperience: "12 years",
        },
        {
          name: "Dr. Asad Ali",
          degree: "MBBS, MS",
          speciality: "Orthopedics",
          workingIn: "Square Hospitals Ltd.",
          totalExperience: "14 years",
        },
        {
          name: "Dr. Sumaiya Ahmed",
          degree: "MBBS, MSc",
          speciality: "Nutrition & Food Science",
          workingIn: "Square Hospitals Ltd.",
          totalExperience: "9 years",
        },
        {
          name: "Dr. Imran Khan",
          degree: "MBBS, MS",
          speciality: "Urology",
          workingIn: "Square Hospitals Ltd.",
          totalExperience: "11 years",
        },
        {
          name: "Dr. Yasmin Akter",
          degree: "MBBS, FCPS",
          speciality: "Ophthalmology",
          workingIn: "Square Hospitals Ltd.",
          totalExperience: "13 years",
        },
        {
          name: "Dr. Hasan Mahmud",
          degree: "MBBS, MD",
          speciality: "Dermatology",
          workingIn: "Square Hospitals Ltd.",
          totalExperience: "12 years",
        },
      ],
    },
    {
      hospitalName: "Dhaka Medical College Hospital",
      hospitalArea: "Shahbag, Dhaka, Bangladesh",
      doctors: [
        {
          name: "Dr. Yasmin Begum",
          degree: "MBBS, FCPS",
          speciality: "Gynae & Obs",
          workingIn: "Dhaka Medical College Hospital",
          totalExperience: "14 years",
        },
        {
          name: "Dr. Ahmed Khan",
          degree: "MBBS, MD",
          speciality: "General Physician",
          workingIn: "Dhaka Medical College Hospital",
          totalExperience: "9 years",
        },
        {
          name: "Dr. Sultana Akhter",
          degree: "MBBS, FCPS",
          speciality: "Dermatology",
          workingIn: "Dhaka Medical College Hospital",
          totalExperience: "13 years",
        },
        {
          name: "Dr. Rezaul Haque",
          degree: "MBBS, FCPS",
          speciality: "Internal Medicine",
          workingIn: "Dhaka Medical College Hospital",
          totalExperience: "11 years",
        },
        {
          name: "Dr. Anika Rahman",
          degree: "MBBS, MD",
          speciality: "Pediatrics",
          workingIn: "Dhaka Medical College Hospital",
          totalExperience: "12 years",
        },
        {
          name: "Dr. Jahangir Alam",
          degree: "MBBS, FCPS",
          speciality: "Gastroenterology",
          workingIn: "Dhaka Medical College Hospital",
          totalExperience: "10 years",
        },
        {
          name: "Dr. Fariha Khan",
          degree: "MBBS, MD",
          speciality: "Psychiatry",
          workingIn: "Dhaka Medical College Hospital",
          totalExperience: "11 years",
        },
        {
          name: "Dr. Kabir Hossain",
          degree: "MBBS, FCPS",
          speciality: "Orthopedics",
          workingIn: "Dhaka Medical College Hospital",
          totalExperience: "14 years",
        },
        {
          name: "Dr. Nusrat Jahan",
          degree: "MBBS, MS",
          speciality: "Urology",
          workingIn: "Dhaka Medical College Hospital",
          totalExperience: "12 years",
        },
        {
          name: "Dr. Aminul Islam",
          degree: "MBBS, FCPS",
          speciality: "Ophthalmology",
          workingIn: "Dhaka Medical College Hospital",
          totalExperience: "13 years",
        },
      ],
    },
    {
      hospitalName: "Bangabandhu Sheikh Mujib Medical University Hospital",
      hospitalArea: "Shahbag, Dhaka, Bangladesh",
      doctors: [
        {
          name: "Dr. Ayesha Siddiqua",
          degree: "MBBS, FCPS",
          speciality: "Psychology",
          workingIn: "Bangabandhu Sheikh Mujib Medical University Hospital",
          totalExperience: "11 years",
        },
        {
          name: "Dr. Rafiqul Islam",
          degree: "MBBS, MD",
          speciality: "Dermatology",
          workingIn: "Bangabandhu Sheikh Mujib Medical University Hospital",
          totalExperience: "12 years",
        },
        {
          name: "Dr. Sahar Ahmed",
          degree: "MBBS, FCPS",
          speciality: "Internal Medicine",
          workingIn: "Bangabandhu Sheikh Mujib Medical University Hospital",
          totalExperience: "10 years",
        },
        {
          name: "Dr. Farida Akhter",
          degree: "MBBS, MD",
          speciality: "Pediatrics",
          workingIn: "Bangabandhu Sheikh Mujib Medical University Hospital",
          totalExperience: "13 years",
        },
        {
          name: "Dr. Kabir Rahman",
          degree: "MBBS, FCPS",
          speciality: "Gastroenterology",
          workingIn: "Bangabandhu Sheikh Mujib Medical University Hospital",
          totalExperience: "11 years",
        },
        {
          name: "Dr. Nafisa Khan",
          degree: "MBBS, MRCP",
          speciality: "Nutrition & Food Science",
          workingIn: "Bangabandhu Sheikh Mujib Medical University Hospital",
          totalExperience: "14 years",
        },
        {
          name: "Dr. Salman Ahmed",
          degree: "MBBS, MS",
          speciality: "Orthopedics",
          workingIn: "Bangabandhu Sheikh Mujib Medical University Hospital",
          totalExperience: "12 years",
        },
        {
          name: "Dr. Sanya Rahman",
          degree: "MBBS, FCPS",
          speciality: "Urology",
          workingIn: "Bangabandhu Sheikh Mujib Medical University Hospital",
          totalExperience: "10 years",
        },
        {
          name: "Dr. Ali Akbar",
          degree: "MBBS, MD",
          speciality: "Ophthalmology",
          workingIn: "Bangabandhu Sheikh Mujib Medical University Hospital",
          totalExperience: "13 years",
        },
        {
          name: "Dr. Fatima Begum",
          degree: "MBBS, FCPS",
          speciality: "General Physician",
          workingIn: "Bangabandhu Sheikh Mujib Medical University Hospital",
          totalExperience: "11 years",
        },
      ],
    },
    {
      hospitalName: "Apollo Hospitals Dhaka",
      hospitalArea: "Bashundhara R/A, Dhaka, Bangladesh",
      doctors: [
        {
          name: "Dr. Sumaiya Khan",
          degree: "MBBS, FCPS",
          speciality: "Gynae & Obs",
          workingIn: "Apollo Hospitals Dhaka",
          totalExperience: "14 years",
        },
        {
          name: "Dr. Imran Chowdhury",
          degree: "MBBS, MD",
          speciality: "General Physician",
          workingIn: "Apollo Hospitals Dhaka",
          totalExperience: "12 years",
        },
        {
          name: "Dr. Amina Haque",
          degree: "MBBS, FCPS",
          speciality: "Dermatology",
          workingIn: "Apollo Hospitals Dhaka",
          totalExperience: "11 years",
        },
        {
          name: "Dr. Zayed Ahmed",
          degree: "MBBS, FCPS",
          speciality: "Internal Medicine",
          workingIn: "Apollo Hospitals Dhaka",
          totalExperience: "13 years",
        },
        {
          name: "Dr. Farah Khan",
          degree: "MBBS, MD",
          speciality: "Pediatrics",
          workingIn: "Apollo Hospitals Dhaka",
          totalExperience: "15 years",
        },
        {
          name: "Dr. Yusuf Islam",
          degree: "MBBS, FCPS",
          speciality: "Gastroenterology",
          workingIn: "Apollo Hospitals Dhaka",
          totalExperience: "10 years",
        },
        {
          name: "Dr. Sofia Rahman",
          degree: "MBBS, MRCP",
          speciality: "Psychiatry",
          workingIn: "Apollo Hospitals Dhaka",
          totalExperience: "12 years",
        },
        {
          name: "Dr. Ahsanullah Khan",
          degree: "MBBS, MS",
          speciality: "Orthopedics",
          workingIn: "Apollo Hospitals Dhaka",
          totalExperience: "14 years",
        },
        {
          name: "Dr. Arifa Akhter",
          degree: "MBBS, FCPS",
          speciality: "Urology",
          workingIn: "Apollo Hospitals Dhaka",
          totalExperience: "11 years",
        },
        {
          name: "Dr. Saifur Rahman",
          degree: "MBBS, MD",
          speciality: "Ophthalmology",
          workingIn: "Apollo Hospitals Dhaka",
          totalExperience: "12 years",
        },
      ],
    },
    {
      hospitalName: "Labaid Hospital",
      hospitalArea: "Dhanmondi, Dhaka, Bangladesh",
      doctors: [
        {
          name: "Dr. Sadia Rahman",
          degree: "MBBS, FCPS",
          speciality: "Gynae & Obs",
          workingIn: "Labaid Hospital",
          totalExperience: "13 years",
        },
        {
          name: "Dr. Noman Ahmed",
          degree: "MBBS, MD",
          speciality: "General Physician",
          workingIn: "Labaid Hospital",
          totalExperience: "11 years",
        },
        {
          name: "Dr. Farzana Chowdhury",
          degree: "MBBS, FCPS",
          speciality: "Dermatology",
          workingIn: "Labaid Hospital",
          totalExperience: "12 years",
        },
        {
          name: "Dr. Arif Hossain",
          degree: "MBBS, FCPS",
          speciality: "Internal Medicine",
          workingIn: "Labaid Hospital",
          totalExperience: "14 years",
        },
        {
          name: "Dr. Ayesha Khan",
          degree: "MBBS, MD",
          speciality: "Pediatrics",
          workingIn: "Labaid Hospital",
          totalExperience: "10 years",
        },
        {
          name: "Dr. Rafiqul Islam",
          degree: "MBBS, FCPS",
          speciality: "Gastroenterology",
          workingIn: "Labaid Hospital",
          totalExperience: "12 years",
        },
        {
          name: "Dr. Samia Akhter",
          degree: "MBBS, MRCP",
          speciality: "Psychiatry",
          workingIn: "Labaid Hospital",
          totalExperience: "11 years",
        },
        {
          name: "Dr. Rezaul Karim",
          degree: "MBBS, MS",
          speciality: "Orthopedics",
          workingIn: "Labaid Hospital",
          totalExperience: "13 years",
        },
        {
          name: "Dr. Tasnim Ahmed",
          degree: "MBBS, FCPS",
          speciality: "Urology",
          workingIn: "Labaid Hospital",
          totalExperience: "12 years",
        },
        {
          name: "Dr. Sabrina Islam",
          degree: "MBBS, MD",
          speciality: "Ophthalmology",
          workingIn: "Labaid Hospital",
          totalExperience: "15 years",
        },
      ],
    },
    {
      hospitalName: "United Hospital",
      hospitalArea: "Gulshan, Dhaka, Bangladesh",
      doctors: [
        {
          name: "Dr. Hasan Mahmud",
          degree: "MBBS, FCPS",
          speciality: "Gynae & Obs",
          workingIn: "United Hospital",
          totalExperience: "12 years",
        },
        {
          name: "Dr. Fatima Ahmed",
          degree: "MBBS, MD",
          speciality: "General Physician",
          workingIn: "United Hospital",
          totalExperience: "11 years",
        },
        {
          name: "Dr. Ayesha Khan",
          degree: "MBBS, FCPS",
          speciality: "Dermatology",
          workingIn: "United Hospital",
          totalExperience: "13 years",
        },
        {
          name: "Dr. Rahim Hasan",
          degree: "MBBS, FCPS",
          speciality: "Internal Medicine",
          workingIn: "United Hospital",
          totalExperience: "10 years",
        },
        {
          name: "Dr. Fatima Begum",
          degree: "MBBS, MD",
          speciality: "Pediatrics",
          workingIn: "United Hospital",
          totalExperience: "14 years",
        },
        {
          name: "Dr. Farhan Ahmed",
          degree: "MBBS, FCPS",
          speciality: "Gastroenterology",
          workingIn: "United Hospital",
          totalExperience: "12 years",
        },
        {
          name: "Dr. Sultana Akter",
          degree: "MBBS, MRCP",
          speciality: "Psychiatry",
          workingIn: "United Hospital",
          totalExperience: "11 years",
        },
        {
          name: "Dr. Anisur Rahman",
          degree: "MBBS, MS",
          speciality: "Orthopedics",
          workingIn: "United Hospital",
          totalExperience: "13 years",
        },
        {
          name: "Dr. Tasnim Khan",
          degree: "MBBS, FCPS",
          speciality: "Urology",
          workingIn: "United Hospital",
          totalExperience: "12 years",
        },
        {
          name: "Dr. Sabrina Rahman",
          degree: "MBBS, MD",
          speciality: "Ophthalmology",
          workingIn: "United Hospital",
          totalExperience: "15 years",
        },
      ],
    },
  ],
};

export default doctors;
